# Generated by Django 3.0.7 on 2020-07-22 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cushmedia', '0005_services'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='category',
            field=models.CharField(choices=[('outdoor', 'outdoor'), ('weddings', 'weddings'), ('portraits', 'portraits'), ('engagement', 'engagement'), ('couples', 'couples'), ('others', 'others')], default='outdoor', max_length=20),
        ),
    ]
