# Generated by Django 3.0.7 on 2020-07-25 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cushmedia', '0006_auto_20200722_1545'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='desc',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='name',
        ),
        migrations.RemoveField(
            model_name='testimonials',
            name='img',
        ),
        migrations.RemoveField(
            model_name='testimonials',
            name='occupation',
        ),
    ]
